[package]
name = "lily"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
 
[dependencies]
easy = "0.1.1"
curl = "0.4.43"
sudo = "0.6.0"
